//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleArticle.ServiceReferenceArticle {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFArticle")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileArticle", Namespace="http://schemas.datacontract.org/2004/07/WCFArticle")]
    [System.SerializableAttribute()]
    public partial class FileArticle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceArticle.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ConsoleArticle.ServiceReferenceArticle.CompositeType GetDataUsingDataContract(ConsoleArticle.ServiceReferenceArticle.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ConsoleArticle.ServiceReferenceArticle.CompositeType> GetDataUsingDataContractAsync(ConsoleArticle.ServiceReferenceArticle.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFileArticles", ReplyAction="http://tempuri.org/IService1/GetAllFileArticlesResponse")]
        ConsoleArticle.ServiceReferenceArticle.FileArticle[] GetAllFileArticles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFileArticles", ReplyAction="http://tempuri.org/IService1/GetAllFileArticlesResponse")]
        System.Threading.Tasks.Task<ConsoleArticle.ServiceReferenceArticle.FileArticle[]> GetAllFileArticlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddArticleToFile", ReplyAction="http://tempuri.org/IService1/AddArticleToFileResponse")]
        void AddArticleToFile(ConsoleArticle.ServiceReferenceArticle.FileArticle article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddArticleToFile", ReplyAction="http://tempuri.org/IService1/AddArticleToFileResponse")]
        System.Threading.Tasks.Task AddArticleToFileAsync(ConsoleArticle.ServiceReferenceArticle.FileArticle article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAllArticlesToFile", ReplyAction="http://tempuri.org/IService1/AddAllArticlesToFileResponse")]
        void AddAllArticlesToFile(ConsoleArticle.ServiceReferenceArticle.FileArticle[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAllArticlesToFile", ReplyAction="http://tempuri.org/IService1/AddAllArticlesToFileResponse")]
        System.Threading.Tasks.Task AddAllArticlesToFileAsync(ConsoleArticle.ServiceReferenceArticle.FileArticle[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifyPrice", ReplyAction="http://tempuri.org/IService1/ModifyPriceResponse")]
        void ModifyPrice(ConsoleArticle.ServiceReferenceArticle.FileArticle article, double newPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifyPrice", ReplyAction="http://tempuri.org/IService1/ModifyPriceResponse")]
        System.Threading.Tasks.Task ModifyPriceAsync(ConsoleArticle.ServiceReferenceArticle.FileArticle article, double newPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateABill", ReplyAction="http://tempuri.org/IService1/CreateABillResponse")]
        void CreateABill(ConsoleArticle.ServiceReferenceArticle.FileArticle[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateABill", ReplyAction="http://tempuri.org/IService1/CreateABillResponse")]
        System.Threading.Tasks.Task CreateABillAsync(ConsoleArticle.ServiceReferenceArticle.FileArticle[] list);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleArticle.ServiceReferenceArticle.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleArticle.ServiceReferenceArticle.IService1>, ConsoleArticle.ServiceReferenceArticle.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ConsoleArticle.ServiceReferenceArticle.CompositeType GetDataUsingDataContract(ConsoleArticle.ServiceReferenceArticle.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ConsoleArticle.ServiceReferenceArticle.CompositeType> GetDataUsingDataContractAsync(ConsoleArticle.ServiceReferenceArticle.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ConsoleArticle.ServiceReferenceArticle.FileArticle[] GetAllFileArticles() {
            return base.Channel.GetAllFileArticles();
        }
        
        public System.Threading.Tasks.Task<ConsoleArticle.ServiceReferenceArticle.FileArticle[]> GetAllFileArticlesAsync() {
            return base.Channel.GetAllFileArticlesAsync();
        }
        
        public void AddArticleToFile(ConsoleArticle.ServiceReferenceArticle.FileArticle article) {
            base.Channel.AddArticleToFile(article);
        }
        
        public System.Threading.Tasks.Task AddArticleToFileAsync(ConsoleArticle.ServiceReferenceArticle.FileArticle article) {
            return base.Channel.AddArticleToFileAsync(article);
        }
        
        public void AddAllArticlesToFile(ConsoleArticle.ServiceReferenceArticle.FileArticle[] list) {
            base.Channel.AddAllArticlesToFile(list);
        }
        
        public System.Threading.Tasks.Task AddAllArticlesToFileAsync(ConsoleArticle.ServiceReferenceArticle.FileArticle[] list) {
            return base.Channel.AddAllArticlesToFileAsync(list);
        }
        
        public void ModifyPrice(ConsoleArticle.ServiceReferenceArticle.FileArticle article, double newPrice) {
            base.Channel.ModifyPrice(article, newPrice);
        }
        
        public System.Threading.Tasks.Task ModifyPriceAsync(ConsoleArticle.ServiceReferenceArticle.FileArticle article, double newPrice) {
            return base.Channel.ModifyPriceAsync(article, newPrice);
        }
        
        public void CreateABill(ConsoleArticle.ServiceReferenceArticle.FileArticle[] list) {
            base.Channel.CreateABill(list);
        }
        
        public System.Threading.Tasks.Task CreateABillAsync(ConsoleArticle.ServiceReferenceArticle.FileArticle[] list) {
            return base.Channel.CreateABillAsync(list);
        }
    }
}
